import AppleIcon from './Apple-icon.svg';
import GoogleIcon from './Google-icon.svg';
import CrossIcon from './Cross-icon.svg';
import HeartDefault from './Heart-default.svg';
import HeartSaved from './Heart-saved.svg';
import Pound from './Pound.svg';
import Dollar from './Dollar.svg';
import Check from './Check.svg';
export {HeartSaved};
export {HeartDefault};
export {AppleIcon};
export {GoogleIcon};
export {CrossIcon};
export {Check};
export {Pound};
export {Dollar};
