import HiFive from './Hi-five.svg';
import Search from './search.svg';
import Looking from './looking.svg';
import Trail from './trail.svg';
import ArmsInL from './armsInL.svg';
export {HiFive};
export {Search};
export {Looking};
export {Trail};
export {ArmsInL};
