name: Lint Codebase
on: push
permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm

      - name: Install Dependencies
        id: install
        run: npm install

      # Run super-linter for linting TypeScript files
      - name: Lint Codebase
        id: super-linter
        uses: super-linter/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: dist/**/*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_ESLINT: true
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_TSX: true
          VALIDATE_JSX: true

          # Disable unnecessary linters
          VALIDATE_BASH: false
          VALIDATE_CHECKOV: false
          VALIDATE_CPP: false
          VALIDATE_ENV: false
          VALIDATE_GROOVY: false
          VALIDATE_RUBY: false
          VALIDATE_KOTLIN: false
          VALIDATE_SHELL_SHFMT: false
          VALIDATE_GITHUB_ACTIONS: false
          VALIDATE_MARKDOWN: false
          VALIDATE_JSCPD: false
          VALIDATE_JSON: false
          VALIDATE_NATURAL_LANGUAGE: false

      # Optionally, if you have ESLint configured for your project:
      - name: Run ESLint
        run: npm run lint # Assumes you have a lint script in your package.json
