name: Lint Codebase
on: push
permissions:
  contents: read
  packages: read
  statuses: write

jobs:
  lint:
    name: Lint Codebase
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm

      - name: Install Dependencies
        id: install
        run: npm install

      # Run super-linter for linting TypeScript files
      - name: Lint Codebase
        id: super-linter
        uses: super-linter/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: main
          FILTER_REGEX_EXCLUDE: dist/**/*
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_TYPESCRIPT_STANDARD: false # Enable TypeScript linting
          VALIDATE_ESLINT: true

      # Optionally, if you have ESLint configured for your project:
      - name: Run ESLint
        run: npm run lint # Assumes you have a lint script in your package.json
