steps:
  - name: Rollbar deploy
    uses: rollbar/github-deploy-action@2.1.1
    id: rollbar_deploy
    with:
      environment: 'development'
      version: ${{ github.sha }}
    env:
      ROLLBAR_ACCESS_TOKEN: ${{ secrets.ROLLBAR_ACCESS_TOKEN }}
      ROLLBAR_USERNAME: ${{ github.actor }}
